import
{
    loadTimeData
}
from './load_time_data.m.js';
loadTimeData.data = {
    "a11yenhanced": "",
    "actionMenuDescription": "Akce",
    "allowDeletingHistory": true,
    "blockedPasswordProtectedDesc": "Tento soubor je zaĹˇifrovanĂ˝ aÂ jeho otevĹ™enĂ­ bylo zablokovĂˇno.",
    "blockedTooLargeDesc": "Tento soubor je na skenovĂˇnĂ­ vÂ cloudu pĹ™Ă­liĹˇ velkĂ˝ aÂ jeho otevĹ™enĂ­ bylo zablokovĂˇno.",
    "browserManagedByOrg": "VĂˇĹˇ \u003Ca href=\"chrome://management\">prohlĂ­ĹľeÄŤ je spravovĂˇn\u003C/a> vaĹˇĂ­ organizacĂ­",
    "clearAll": "Vymazat vĹˇe",
    "clearSearch": "Vymazat vyhledĂˇvĂˇnĂ­",
    "controlCancel": "ZruĹˇit",
    "controlPause": "Pozastavit",
    "controlRemoveFromList": "Odstranit ze seznamu",
    "controlRemoveFromListAriaLabel": "Odstranit ze seznamu soubor $1",
    "controlResume": "PokraÄŤovat",
    "controlRetry": "Opakovat",
    "controlShowInFolder": "Zobrazit ve sloĹľce",
    "controlledByUrl": "StaĹľeno pomocĂ­ rozĹˇĂ­Ĺ™enĂ­ \u003Ca href=\"$1\">$2\u003C/a>",
    "dangerDiscard": "Zahodit",
    "dangerDownloadDesc": "Tento soubor je nebezpeÄŤnĂ˝, proto jej Chrome zablokoval.",
    "dangerFileDesc": "Tento typ souboru mĹŻĹľe poĹˇkodit vĂˇĹˇ poÄŤĂ­taÄŤ.",
    "dangerRestore": "Ponechat nebezpeÄŤnĂ˝ soubor",
    "dangerSave": "UloĹľit",
    "dangerSettingsDesc": "Tento soubor mĹŻĹľe bĂ˝t nebezpeÄŤnĂ˝, proto jej Chrome zablokoval.",
    "dangerUncommonDesc": "Tento soubor se bÄ›ĹľnÄ› nestahuje aÂ mĹŻĹľe bĂ˝t nebezpeÄŤnĂ˝.",
    "deepScannedOpenedDangerousDesc": "StahovanĂ˝ soubor obsahuje malware.",
    "deepScannedSafeDesc": "SkenovĂˇnĂ­ bylo dokonÄŤeno, nebyly nalezeny ĹľĂˇdnĂ© problĂ©my.",
    "downloads": "StaĹľenĂ© soubory",
    "fontfamily": "'Segoe UI', Tahoma, sans-serif",
    "fontsize": "75%",
    "inIncognito": "StaĹľeno vÂ anonymnĂ­m reĹľimu",
    "isManaged": false,
    "language": "cs",
    "mixedContentDownloadDesc": "Tento soubor nelze bezpeÄŤnÄ› stĂˇhnout.",
    "moreActions": "DalĹˇĂ­ akce",
    "noDownloads": "Zde se zobrazujĂ­ staĹľenĂ© soubory",
    "noSearchResults": "Nebyly nalezeny ĹľĂˇdnĂ© vĂ˝sledky",
    "openDownloadsFolder": "OtevĹ™Ă­t sloĹľku staĹľenĂ˝ch souborĹŻ",
    "requestsApVerdicts": false,
    "search": "Hledat staĹľenĂ© soubory",
    "searchResultsPlural": "VĂ˝sledky pro dotaz $2 ($1)",
    "searchResultsSingular": "1 vĂ˝sledek pro dotaz $1",
    "sensitiveContentBlockedDesc": "Tento soubor byl zablokovĂˇn, protoĹľe zahrnuje citlivĂ˝ obsah.",
    "sensitiveContentWarningDesc": "Tento soubor obsahuje citlivĂ˝ obsah.",
    "statusCancelled": "ZruĹˇeno",
    "statusRemoved": "SmazĂˇno",
    "textdirection": "ltr",
    "title": "StaĹľenĂ© soubory",
    "toastClearedAll": "VĹˇe bylo vymazĂˇno",
    "toastRemovedFromList": "Ze seznamu byl odstranÄ›n soubor $1",
    "undo": "VrĂˇtit zpÄ›t",
    "undoDescription": "StisknutĂ­m Ctrl+Z vrĂˇtĂ­te provedenou akci zpÄ›t"
};